---
micronaut:
  application:
    name: azdio-cache
  metrics:
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  server:
    port: 9050
endpoints:
  all:
    enabled: true
    sensitive: false
---
hazelcast:
  config:
    instance-name: mdw
    group:
      name: mdw
      password: mdw
    network:
      port:
        5701
      interfaces:
        enabled: false
        public-address:
        - 127.0.0.1
      join:
        multicast:
          enabled: true
        tcp-ip:
          enabled: false
    properties:
      hazelcast.logging.type: slf4j
      hazelcast.shutdownhook.policy: GRACEFUL
      #hazelcast.shutdownhook.policy: SHUTDOWN
  management-center:
    enabled: true
    update-interval: 5
    url: http://localhost:9091/hazelcast-mancenter
    